Java:
###############################################
# Run GitHub's Super Linter against code base #
###############################################

name: GitHub's Super Linter

on: [push, pull_request]

jobs:
 run-linters:
   name: GitHub's Super Linter
   runs-on: ubuntu-latest

   steps:
     - name: Check out Git repository
       uses: actions/checkout@master
      
     - name: Run GitHub Super Linter
       uses: github/super-linter@main
       env:
         VALIDATE_ALL_CODEBASE: true
         VALIDATE_JAVASCRIPT_STANDARD: false
         VALIDATE_CLANG_FORMAT: false
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

java -jar ~/scripts/checkstyle.jar -c ~/scripts/mr-coxall_checks.xml *.java
[![GitHub's Super Linter](https://github.com/<OWNER>/<REPOSITORY>/workflows/GitHub's%20Super%20Linter/badge.svg)](https://github.com/<OWNER>/<REPOSITORY>/actions)
google-java-format -i *.java
Swift:
###################################
# Run SwiftLint against code base #
###################################
name: SwiftLint
on: [push, pull_request]
jobs:
  SwiftLint--strict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
